module.exports = {
  // AF: 'Afghanistan',
  // AM: 'Armenia',
  // AZ: 'Azerbaijan',
  // BH: 'Bahrain',
  // BD: 'Bangladesh',
  // BT: 'Bhutan',
  // IO: 'British Indian Ocean Territory',
  // BN: 'Brunei Darussalam',
  // KH: 'Cambodia',
  // CN: 'China',
  // CX: 'Christmas Island',
  // CC: 'Cocos (Keeling) Islands',
  // CY: 'Cyprus',
  // GE: 'Georgia',
  // HK: 'Hong Kong',
  // IN: 'India',
  // ID: 'Indonesia',
  // IR: 'Iran',
  // IQ: 'Iraq',
  // IL: 'Israel',
  // JP: 'Japan',
  // JO: 'Jordan',
  // KZ: 'Kazakhstan',
  // KP: 'North Korea',
  // KR: 'South Korea',
  // KW: 'Kuwait',
  // KG: 'Kyrgyzstan',
  // LA: 'Lao People\'s Democratic Republic',
  // LB: 'Lebanon',
  // MO: 'Macao',
  // MY: 'Malaysia',
  // MV: 'Maldives',
  // MN: 'Mongolia',
  // MM: 'Myanmar',
  // NP: 'Nepal',
  // OM: 'Oman',
  // PK: 'Pakistan',
  // PS: 'Palestinia',
  // PH: 'Philippines',
  // QA: 'Qatar',
  // SA: 'Saudi Arabia',
  // SG: 'Singapore',
  // LK: 'Sri Lanka',
  // SY: 'Syrian Arab Republic',
  // TW: 'Taiwan',
  // TJ: 'Tajikistan',
  // TH: 'Thailand',
  // TL: 'Timor-leste',
  // TR: 'Turkey',
  // TM: 'Turkmenistan',
  // AE: 'United Arab Emirates',
  // UZ: 'Uzbekistan',
  // VN: 'Vietnam',
  // YE: 'Yemen',
  // AX: 'Åland Islands',
  // AL: 'Albania',
  // AD: 'Andorra',
  // AT: 'Austria',
  // BY: 'Belarus',
  // BE: 'Belgium',
  // BA: 'Bosnia and Herzegovina',
  // BG: 'Bulgaria',
  // HR: 'Croatia',
  // CZ: 'Czech Republic',
  // DK: 'Denmark',
  // EE: 'Estonia',
  // FO: 'Faroe Islands',
  // FI: 'Finland',
  // FR: 'France',
  // DE: 'Germany',
  // GI: 'Gibraltar',
  // GR: 'Greece',
  // GG: 'Guernsey',
  // VA: 'Holy See (Vatican City State)',
  // HU: 'Hungary',
  // IS: 'Iceland',
  // IE: 'Ireland',
  // IM: 'Isle of Man',
  // IT: 'Italy',
  // JE: 'Jersey',
  // LV: 'Latvia',
  // LI: 'Liechtenstein',
  // LT: 'Lithuania',
  // LU: 'Luxembourg',
  // MK: 'Macedonia',
  // MT: 'Malta',
  // MD: 'Moldova',
  // MC: 'Monaco',
  // ME: 'Montenegro',
  // NL: 'Netherlands',
  // NO: 'Norway',
  // PL: 'Poland',
  // PT: 'Portugal',
  // RO: 'Romania',
  // RU: 'Russian Federation',
  // SM: 'San Marino',
  // RS: 'Serbia',
  // SK: 'Slovakia',
  // SI: 'Slovenia',
  // ES: 'Spain',
  // SJ: 'Svalbard and Jan Mayen',
  // SE: 'Sweden',
  // CH: 'Switzerland',
  // UA: 'Ukraine',
  // GB: 'United Kingdom',
  // DZ: 'Algeria',
  // AO: 'Angola',
  // BJ: 'Benin',
  // BW: 'Botswana',
  // BF: 'Burkina Faso',
  // BI: 'Burundi',
  // CM: 'Cameroon',
  // CV: 'Cape Verde',
  // CF: 'Central African Republic',
  // TD: 'Chad',
  // KM: 'Comoros',
  // CG: 'Congo',
  // CD: 'The Democratic Republic of The Congo',
  // CI: 'Cote D\'ivoire',
  // DJ: 'Djibouti',
  // EG: 'Egypt',
  // GQ: 'Equatorial Guinea',
  // ER: 'Eritrea',
  // ET: 'Ethiopia',
  // GA: 'Gabon',
  // GM: 'Gambia',
  // GH: 'Ghana',
  // GN: 'Guinea',
  // GW: 'Guinea-bissau',
  // KE: 'Kenya',
  // LS: 'Lesotho',
  // LR: 'Liberia',
  // LY: 'Libya',
  // MG: 'Madagascar',
  // MW: 'Malawi',
  // ML: 'Mali',
  // MR: 'Mauritania',
  // MU: 'Mauritius',
  // YT: 'Mayotte',
  // MA: 'Morocco',
  // MZ: 'Mozambique',
  // NA: 'Namibia',
  // NE: 'Niger',
  // NG: 'Nigeria',
  // RE: 'Reunion',
  // RW: 'Rwanda',
  // SH: 'Saint Helena',
  // ST: 'Sao Tome and Principe',
  // SN: 'Senegal',
  // SC: 'Seychelles',
  // SL: 'Sierra Leone',
  // SO: 'Somalia',
  // ZA: 'South Africa',
  // SS: 'South Sudan',
  // SD: 'Sudan',
  // SZ: 'Swaziland',
  // TZ: 'Tanzania, United Republic of',
  // TG: 'Togo',
  // TN: 'Tunisia',
  // UG: 'Uganda',
  // EH: 'Western Sahara',
  // ZM: 'Zambia',
  // ZW: 'Zimbabwe',
  // AS: 'American Samoa',
  // AU: 'Australia',
  // CK: 'Cook Islands',
  // FJ: 'Fiji',
  // PF: 'French Polynesia',
  // GU: 'Guam',
  // KI: 'Kiribati',
  // MH: 'Marshall Islands',
  // FM: 'Micronesia',
  // NR: 'Nauru',
  // NC: 'New Caledonia',
  // NZ: 'New Zealand',
  // NU: 'Niue',
  // NF: 'Norfolk Island',
  // MP: 'Northern Mariana Islands',
  // PW: 'Palau',
  // PG: 'Papua New Guinea',
  // PN: 'Pitcairn',
  // WS: 'Samoa',
  // SB: 'Solomon Islands',
  // TK: 'Tokelau',
  // TO: 'Tonga',
  // TV: 'Tuvalu',
  // UM: 'United States Minor Outlying Islands',
  // VU: 'Vanuatu',
  // WF: 'Wallis and Futuna',
  // AI: 'Anguilla',
  // AG: 'Antigua and Barbuda',
  // AW: 'Aruba',
  // BS: 'Bahamas',
  // BB: 'Barbados',
  // BZ: 'Belize',
  // BM: 'Bermuda',
  // BQ: 'Bonaire, Sint Eustatius and Saba',
  // CA: 'Canada',
  // KY: 'Cayman Islands',
  // CR: 'Costa Rica',
  // CW: 'Curaçao',
  // CU: 'Cuba',
  // DM: 'Dominica',
  // DO: 'Dominican Republic',
  // SV: 'El Salvador',
  // GL: 'Greenland',
  // GD: 'Grenada',
  // GP: 'Guadeloupe',
  // GT: 'Guatemala',
  // HT: 'Haiti',
  // HN: 'Honduras',
  // JM: 'Jamaica',
  // MQ: 'Martinique',
  // MX: 'Mexico',
  // MS: 'Montserrat',
  // NI: 'Nicaragua',
  // PA: 'Panama',
  // PR: 'Puerto Rico',
  // BL: 'Saint Barthélemy',
  // KN: 'Saint Kitts and Nevis',
  // LC: 'Saint Lucia',
  // MF: 'Saint Martin',
  // PM: 'Saint Pierre and Miquelon',
  // VC: 'Saint Vincent and The Grenadines',
  // SX: 'Sint Maarten',
  // TT: 'Trinidad and Tobago',
  // TC: 'Turks and Caicos Islands',
  // US: 'United States',
  // VG: 'Virgin Islands, British',
  // VI: 'Virgin Islands, U.S.',
  // AQ: 'Antarctica',
  // BV: 'Bouvet Island',
  // TF: 'French Southern Territories',
  // HM: 'Heard Island and Mcdonald Islands',
  // GS: 'South Georgia and The South Sandwich Islands',
  // AR: 'Argentina',
  // BO: 'Bolivia',
  // BR: 'Brazil',
  // CL: 'Chile',
  // CO: 'Colombia',
  // EC: 'Ecuador',
  // FK: 'Falkland Islands (Malvinas)',
  // GF: 'French Guiana',
  // GY: 'Guyana',
  // PY: 'Paraguay',
  // PE: 'Peru',
  // SR: 'Suriname',
  // UY: 'Uruguay',
  // VE: 'Venezuela',
}